/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AetheriumAvatar__factory } from "./AetheriumAvatar__factory";
export { AetheriumShard__factory } from "./AetheriumShard__factory";
export { GameManager__factory } from "./GameManager__factory";
