/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AetheriumAvatar } from "./AetheriumAvatar";
export type { AetheriumShard } from "./AetheriumShard";
export type { GameManager } from "./GameManager";
